# Generated by Django 4.2.3 on 2023-07-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('preferred_time', models.DateTimeField()),
                ('other_availability', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('contingent', 'Contingent'), ('under contract', 'Under Contract'), ('pending', 'Pending')], max_length=15)),
                ('notes', models.TextField()),
            ],
        ),
    ]
