# Generated by Django 4.2.3 on 2023-07-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_showing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showing',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('contingent', 'contingent'), ('under contract', 'under contract'), ('pending', 'pending')], max_length=15),
        ),
    ]
