# Generated by Django 4.2.3 on 2023-07-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_showing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showing',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('contingent', 'Contingent'), ('under contract', 'Under Contract'), ('pending', 'Pending')], max_length=15),
        ),
    ]
